name: cd

on:
  workflow_dispatch:
  push:
    tags: [ v-* ]

env:
  project-name: ${{ secrets.PROJECT_NAME }}
  client-directory: ./client/
  server-directory: ./server/
  node-version: 20.x
  python-version: "3.10"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  sam-deploy:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.server-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build
        run: sam build --use-container
      - name: Deploy
        run: sam deploy --stack-name ${{ env.project-name }}
  www-build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.client-directory }}
    needs: sam-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: ${{ env.client-directory }}node_modules/
          key: node-modules-${{ env.node-version }}-${{ hashFiles('./**/yarn.lock') }}
      - name: Install dependencies
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --non-interactive --production
      - name: Append data to `.env.local`
        run: chmod +x ./initializer.sh && ./initializer.sh ${{ env.project-name }}
      - name: Build with Next.js
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.client-directory }}dist/
  www-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: www-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
